package templates

const fileTpl = `// Code generated by protoc-gen-zap
// source: {{ .InputPath }}
// DO NOT EDIT!!!
package {{ .Package.GoName }}
import (
	"go.uber.org/zap/zapcore"
	"github.com/bigbluedisco/protoc-gen-zap/utils"
)

{{ range .AllMessages }}
	{{ template "message" . }}
{{ end }}
`
