// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.16.0
// source: zap/zap.proto

package zap

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObfuscationType int32

const (
	ObfuscationType_OBFUSCATION_TYPE_UNSPECIFIED ObfuscationType = 0
	ObfuscationType_HIDE                         ObfuscationType = 1 // Remove field and value from log entierly
	ObfuscationType_STARS                        ObfuscationType = 2 // Replace value by 3 stars
)

// Enum value maps for ObfuscationType.
var (
	ObfuscationType_name = map[int32]string{
		0: "OBFUSCATION_TYPE_UNSPECIFIED",
		1: "HIDE",
		2: "STARS",
	}
	ObfuscationType_value = map[string]int32{
		"OBFUSCATION_TYPE_UNSPECIFIED": 0,
		"HIDE":                         1,
		"STARS":                        2,
	}
)

func (x ObfuscationType) Enum() *ObfuscationType {
	p := new(ObfuscationType)
	*p = x
	return p
}

func (x ObfuscationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObfuscationType) Descriptor() protoreflect.EnumDescriptor {
	return file_zap_zap_proto_enumTypes[0].Descriptor()
}

func (ObfuscationType) Type() protoreflect.EnumType {
	return &file_zap_zap_proto_enumTypes[0]
}

func (x ObfuscationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObfuscationType.Descriptor instead.
func (ObfuscationType) EnumDescriptor() ([]byte, []int) {
	return file_zap_zap_proto_rawDescGZIP(), []int{0}
}

var file_zap_zap_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*ObfuscationType)(nil),
		Field:         50002,
		Name:          "zap.obfuscation_type",
		Tag:           "varint,50002,opt,name=obfuscation_type,enum=zap.ObfuscationType",
		Filename:      "zap/zap.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional zap.ObfuscationType obfuscation_type = 50002;
	E_ObfuscationType = &file_zap_zap_proto_extTypes[0]
)

var File_zap_zap_proto protoreflect.FileDescriptor

var file_zap_zap_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x7a, 0x61, 0x70, 0x2f, 0x7a, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x7a, 0x61, 0x70, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x48, 0x0a, 0x0f, 0x4f, 0x62, 0x66, 0x75, 0x73, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x1c, 0x4f, 0x42, 0x46,
	0x55, 0x53, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x48,
	0x49, 0x44, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x52, 0x53, 0x10, 0x02,
	0x3a, 0x60, 0x0a, 0x10, 0x6f, 0x62, 0x66, 0x75, 0x73, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0xd2, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x7a, 0x61,
	0x70, 0x2e, 0x4f, 0x62, 0x66, 0x75, 0x73, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0f, 0x6f, 0x62, 0x66, 0x75, 0x73, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x62, 0x69, 0x67, 0x62, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x7a, 0x61, 0x70, 0x2f, 0x7a, 0x61, 0x70,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zap_zap_proto_rawDescOnce sync.Once
	file_zap_zap_proto_rawDescData = file_zap_zap_proto_rawDesc
)

func file_zap_zap_proto_rawDescGZIP() []byte {
	file_zap_zap_proto_rawDescOnce.Do(func() {
		file_zap_zap_proto_rawDescData = protoimpl.X.CompressGZIP(file_zap_zap_proto_rawDescData)
	})
	return file_zap_zap_proto_rawDescData
}

var file_zap_zap_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zap_zap_proto_goTypes = []interface{}{
	(ObfuscationType)(0),              // 0: zap.ObfuscationType
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_zap_zap_proto_depIdxs = []int32{
	1, // 0: zap.obfuscation_type:extendee -> google.protobuf.FieldOptions
	0, // 1: zap.obfuscation_type:type_name -> zap.ObfuscationType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zap_zap_proto_init() }
func file_zap_zap_proto_init() {
	if File_zap_zap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zap_zap_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_zap_zap_proto_goTypes,
		DependencyIndexes: file_zap_zap_proto_depIdxs,
		EnumInfos:         file_zap_zap_proto_enumTypes,
		ExtensionInfos:    file_zap_zap_proto_extTypes,
	}.Build()
	File_zap_zap_proto = out.File
	file_zap_zap_proto_rawDesc = nil
	file_zap_zap_proto_goTypes = nil
	file_zap_zap_proto_depIdxs = nil
}
